version: 2.1

executors:
  base:
    docker:
    - image: circleci/openjdk:8-jdk

jobs:
  compile:
    executor: base
    steps:
    - checkout
    - restore_cache:
        keys:
        - hello-world-{{ checksum "grails-app/conf/BuildConfig.groovy" }}
    - run:
        name: Compile
        working_direcrory: /home/circleci/project
        command: ./grailsw compile --refresh-dependencies --non-interactive
    - save_cache:
        key: hello-world-{{ checksum "grails-app/conf/BuildConfig.groovy" }}
        paths:
        - /home/circleci/.m2
    - persist_to_workspace:
        root: /home/circleci # configure this to something else with env var
        paths: 
        - .m2
        - .grails
  
  unit_test:
    executor: base
    steps:
    - checkout
    - attach_workspace:
        at: /home/circleci
    - run:
        name: Unit Tests
        working_direcrory: /home/circleci/project
        command: ./grailsw -coverage -xml test-app unit':' --non-interactive
    - persist_to_workspace:
        root: /home/circleci # configure this to something else with env var
        paths: 
        - .m2
        - .grails

  package:
    executor: base
    steps:
    - checkout
    - attach_workspace:
        at: /home/circleci
    - run:
        name: Package
        working_direcrory: /home/circleci/project
        command: ./grailsw war

workflows:
  version: 2
  capi:
    jobs:
    - compile:
        filters:
          branches:
            only: master
    - unit_test:
        name: Unit Tests
        requires: 
        - compile
    # Example
    - unit_test:
        name: Functional Tests
        requires: 
        - compile
    # End Example
    - package: 
        requires:
        - Unit Tests
        - Functional Tests

          